### ISSUE TITLE
Missing "Manifest" of event versions in a edition

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/eiffel#342]
### Description

Today there is no one place to see which version of events that are part of an edition.

### Motivation

If I today want to see all version of each event in a Edition I need to go hunting for it or create my own script. 

### Exemplification

Maybe create a YAML file like a manifest (one for each edition)

```YAML
edition: Arica
events:
   EiffelActivityTriggeredEvent: 4.2.0
   EiffelActivityCanceledEvent: 3.2.0
```

### Benefits

Having one place to see what versions of a event included in the edition make it easier for the consumer of new editions. It would be best if the file was programmatically parseable.

### Possible Drawbacks

None that I can think of

**Comment by magnusbaeck** [comment]
I think this is an excellent idea. I could use it both the Jenkins plugin and in eiffelevents-sdk-go where I currently have to [read the contents of the directories at each edition tag](https://github.com/eiffel-community/eiffelevents-sdk-go/blob/6a25112444bd5c27504e0ebf665e65144263afb1/internal/cmd/editiongen/main.go#L87-L128). Doing that is about 40 LOC so it's not too bad but it would be nice to be able to get rid of it.

I would prefer a single file with information about all editions. Single files are easier to transport and clients won't have to discover/guess that names of the editions. Schema suggestion:

```yaml
---
- name: Arica
  tag: edition-arica
  events:
    EiffelActivityTriggeredEvent: 4.2.0
    EiffelActivityCanceledEvent: 3.2.0
- name: Lyon
  tag: edition-lyon
  events:
    EiffelActivityTriggeredEvent: 4.1.0
    EiffelActivityCanceledEvent: 3.1.0
...
```
